// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskTracker.Api.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskTracker.Api.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Assignee = "Alice",
                            CreatedAt = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "Done",
                            Title = "Set up Project Structure"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Assignee = "Bob",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "InProgress",
                            Title = "Configure PostgreSQL Database"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Assignee = "Alice",
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            Status = "Todo",
                            Title = "Implement REST API Endpoints"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Assignee = "Charlie",
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "Todo",
                            Title = "Design Premium React Frontend"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Assignee = "Bob",
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Status = "Todo",
                            Title = "Write Unit Tests and Verify"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
